all_methods = [
        "Auto Attack",
        "Auto Projected Gradient Descent (Auto-PGD)",
        "Auto Conjugate Gradient (Auto-CG)",
        "Boundary Attack / Decision-Based Attack",
        "Carlini and Wagner L_inf Attack",
        "Composite Adversarial Attack - PyTorch",
        "DeepFool",
        "Elastic Net Attack",
        "Fast Gradient Method (FGM)",
        "Feature Adversaries - Numpy",
        "Geometric Decision Based Attack",
        "High Confidence Low Uncertainty Attack",
        "HopSkipJump Attack",
        "Basic Iterative Method (BIM)",
        "Projected Gradient Descent (PGD) - PyTorch",
        "NewtonFool",
        "PixelAttack",
        "ThresholdAttack",
        "JSMA",
        "Shadow Attack",
        "Sign-OPT",
        "Simple Black-box",
        "Spatial Transform",
        "Square Attack",
        "Universal Perturbation",
        "Virtual Adv. Method"
]